spring.application.name=booking-system

#Connessione al database PostgresSQL
spring.datasoruce.url = jdbc:postgresql://localhost:5432/boking_db
spring.datasource.username=user
spirng.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

#Hibernate / JPA
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
